# Deploy VeritasAI React Application via docs folder
name: Deploy VeritasAI App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Build and update docs folder
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
        
    - name: Build React application
      working-directory: ./frontend
      run: npm run build
    
    - name: Copy build to docs folder
      run: |
        rm -rf docs
        mkdir docs
        cp -r frontend/dist/* docs/
        echo "Build copied to docs folder:"
        ls -la docs/
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "🚀 Deploy VeritasAI app to docs folder" -a || exit 0
        git push
